apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i3jrylzv2-go 
  janus-idp.io/tekton: i3jrylzv2-go
  backstage.io/kubernetes-id: i3jrylzv2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i3jrylzv2-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml